import { ScanInput, AnalysisReport } from './types';
import { generateMockReport } from './mockData';

export async function runAnalysis(input: ScanInput): Promise<AnalysisReport> {
  // Try API-based analysis first
  try {
    const response = await fetch('/api/analyze', {
      method: 'POST',
      headers: { 'Content-Type': 'application/json' },
      body: JSON.stringify(input),
    });

    if (response.ok) {
      const data = await response.json();
      return data;
    }
  } catch {
    // Fall through to mock
  }

  // Fallback to client-side mock generation
  return generateMockReport(input);
}

export function saveReport(report: AnalysisReport): void {
  if (typeof window === 'undefined') return;
  const existing = getSavedReports();
  const updated = [report, ...existing.filter(r => r.id !== report.id)];
  localStorage.setItem('majlis-reports', JSON.stringify(updated));
}

export function getSavedReports(): AnalysisReport[] {
  if (typeof window === 'undefined') return [];
  try {
    const data = localStorage.getItem('majlis-reports');
    return data ? JSON.parse(data) : [];
  } catch {
    return [];
  }
}

export function getReportById(id: string): AnalysisReport | null {
  const reports = getSavedReports();
  return reports.find(r => r.id === id) || null;
}

export function deleteReport(id: string): void {
  const reports = getSavedReports();
  const filtered = reports.filter(r => r.id !== id);
  localStorage.setItem('majlis-reports', JSON.stringify(filtered));
}

export function generateInvestorBrief(report: AnalysisReport): string {
  const { input, marketReadinessScore, opportunityLevel, recommendation, executiveSummary, radarData, risks, competitors } = report;

  const topRisks = risks.filter(r => r.severity === 'critical' || r.severity === 'high').map(r => r.name).join(', ');
  const topScores = radarData.sort((a, b) => b.score - a.score).slice(0, 3).map(d => `${d.dimension} (${d.score}/100)`).join(', ');
  const competitorNames = competitors.slice(0, 4).map(c => c.name).join(', ');

  return `INVESTOR BRIEF — ${input.companyName.toUpperCase()}
Market Expansion: ${input.currentCountry} → ${input.targetCountry}

EXECUTIVE SUMMARY
${executiveSummary}

MARKET READINESS SCORE: ${marketReadinessScore}/100
Opportunity Level: ${opportunityLevel}
Strategic Recommendation: ${recommendation}

KEY STRENGTHS
${topScores}

KEY RISKS
${topRisks || 'No critical risks identified'}

COMPETITIVE LANDSCAPE
Key competitors: ${competitorNames}
Differentiation: ${input.product}

INVESTMENT ASK
Budget: ${input.budget}
Timeline: ${input.timeline}
Stage: ${input.stage}

TARGET MARKET
Customer: ${input.targetCustomer}
Industry: ${input.industry}

STRATEGIC APPROACH
Phase 1: Regulatory setup and e-commerce launch (Weeks 1–4)
Phase 2: Influencer marketing and brand awareness (Weeks 5–8)
Phase 3: Performance analysis and retail expansion (Weeks 9–12)

———
Generated by Majlis Radar — AI Market Entry Council
This analysis is AI-assisted and should be validated with local market experts before execution.`;
}
